<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationIcon>Assets\SWBF3Icon.ico</ApplicationIcon>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.5" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.5" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.5" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.5" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.5" />
    <PackageReference Include="Avalonia.Headless" Version="11.2.5" />
    <!-- Required by the VS Code previewer loader -->
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="11.2.5" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>
</Project>